### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by richb-hanover** [chrissanders/FlowBAT#27]
I had earlier reported a problem with installing FlowBAT (#25), but realize that my report was flawed. I spent some time to create a reproducible test case using a Docker instance that shows where things go wrong. I put the Dockerfile as well as the build procedure in https://github.com/richb-hanover/SiLK-in-Docker

To see the installation process, read the Dockerfile in that repo. After using the "To start debugging" steps, I see this error:

```
node /home/flowbat/FlowBAT/private/bundle/main.js

/home/flowbat/FlowBAT/private/bundle/programs/server/node_modules/fibers/future.js:245
            throw(ex);
                  ^
TypeError: Cannot read property 'isDebug' of undefined
    at lib/app.coffee:162:39
    at lib/app.coffee:1:1
    at /home/flowbat/FlowBAT/private/bundle/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/flowbat/FlowBAT/private/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /home/flowbat/FlowBAT/private/bundle/programs/server/boot.js:117:5
```
My github repo shows how to reproduce this failure. Any thoughts? Many thanks.

**Comment by richb-hanover** [comment]
Using Meteor 0.9.1 seems to address the install problem in the install_flowbat_ubuntu.sh script - change the Meteor line in the script to say:

```
curl https://install.meteor.com/?release=0.9.1 | /bin/sh
```
