### ISSUE TITLE
Installation issue using ./install_flowbat_ubuntu.sh

### ISSUE THREAD

**Issue by vv3** [chrissanders/FlowBAT#33]
Running the installation script 'install_flowbat_ubuntu.sh' on a freshly
installed Ubuntu Xenial server results in the following error message:

```
...
Setting up mongodb-server (1:2.6.10-0ubuntu1) ...
Adding system user `mongodb' (UID 107) ...
Adding new user `mongodb' (UID 107) with group `nogroup' ...
Not creating home directory `/var/lib/mongodb'.
Adding group `mongodb' (GID 111) ...
Done.
Adding user `mongodb' to group `mongodb' ...
Adding user mongodb to group mongodb
Done.
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu4) ...
Processing triggers for ureadahead (0.100.0-19) ...

> meteor-dev-bundle@0.0.0 install /home/flowbat/FlowBAT/private/bundle/programs/server
> node npm-rebuild.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flowbat/.npm/_logs/2018-02-08T12_51_35_981Z-debug.log
```
The log file is attched
[2018-02-08T12_51_35_981Z-debug.log](https://github.com/chrissanders/FlowBAT/files/1707082/2018-02-08T12_51_35_981Z-debug.log)

**Comment by kroem** [comment]
I have the same problem. Tested on fresh 16.04 KVM VM and LXC (originally though it might have been a LXC problem)

**Comment by afgibson1** [comment]
I encounter the same error on multiple VM and bare metal Ubuntu 16.04 servers.

**Comment by automayt** [comment]
These elifecycle errors should be fixed with the new installer. 

https://github.com/chrissanders/FlowBAT/commit/3cd3c54ee338c970f364792dfe1e46919ecede47
