### ISSUE TITLE
error while installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by shibumi** [chrissanders/FlowBAT#34]
I get the following error while installing on Ubuntu 16.04 with your installing script:
```
[...]
Done.
Adding user `mongodb' to group `mongodb' ...
Adding user mongodb to group mongodb
Done.
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...

> fibers@2.0.0 install /home/flowbat/FlowBAT/private/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /home/flowbat/FlowBAT/private/bundle/programs/server
> node npm-rebuild.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flowbat/.npm/_logs/2018-02-27T16_56_38_332Z-debug.log
Created symlink from /etc/systemd/system/default.target.wants/flowbat.service to /lib/systemd/system/flowbat.service.
```

**Comment by shibumi** [comment]
Duplicate with: https://github.com/chrissanders/FlowBAT/issues/33
